# Generated by Django 5.0.4 on 2026-02-27 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_district_customuser_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='shirt_size',
            field=models.CharField(blank=True, choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=5, null=True),
        ),
    ]
