# Generated by Django 5.0.4 on 2026-03-01 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customuser_last_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_judge',
            field=models.BooleanField(default=False),
        ),
    ]
