# Generated by Django 5.0.4 on 2026-03-06 01:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('input_txt', models.TextField(blank=True, null=True)),
                ('output_txt', models.TextField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('time_limit', models.IntegerField(default=1000)),
                ('memory_limit', models.IntegerField(default=64)),
                ('difficulty', models.IntegerField(default=1)),
                ('sample_tests', models.IntegerField(default=0)),
                ('test_file', models.FileField(blank=True, null=True, upload_to='problem/test/')),
                ('submission_count', models.IntegerField(default=0)),
                ('accepted_count', models.IntegerField(default=0)),
                ('is_verified', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, to='problems.problemtag')),
            ],
        ),
    ]
