# Generated by Django 5.0.4 on 2026-03-06 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_problem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='test_file',
            field=models.FileField(blank=True, null=True, upload_to='problems/test/'),
        ),
    ]
