# Generated by Django 5.0.4 on 2026-03-08 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0003_alter_problem_test_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='description',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='input_txt',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='note',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='output_txt',
        ),
        migrations.AddField(
            model_name='problem',
            name='statement',
            field=models.TextField(default='12'),
        ),
        migrations.CreateModel(
            name='ProblemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='problems/image/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='problems.problem')),
            ],
        ),
    ]
