# Generated by Django 5.0.4 on 2026-03-08 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0005_alter_problem_statement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='statement',
            field=models.TextField(blank=True, null=True),
        ),
    ]
