# Generated by Django 5.0.4 on 2026-03-08 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0006_alter_problem_statement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='sample_tests',
            new_name='test_count',
        ),
        migrations.CreateModel(
            name='SampleTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.TextField()),
                ('output_data', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='problems.problem')),
            ],
        ),
    ]
