# Generated by Django 5.0.4 on 2026-03-08 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0007_rename_sample_tests_problem_test_count_sampletest'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemimage',
            name='original_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
