# Generated by Django 5.0.4 on 2026-03-11 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0008_problemimage_original_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='languages/')),
                ('language', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=255)),
                ('runtime', models.CharField(blank=True, max_length=255, null=True)),
                ('mode', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
