# Generated by Django 5.0.4 on 2026-03-11 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0009_language'),
    ]

    operations = [
        migrations.RenameField(
            model_name='language',
            old_name='mode',
            new_name='mime',
        ),
    ]
