# Generated by Django 5.0.4 on 2026-03-13 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0010_rename_mode_language_mime'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='languages',
            field=models.ManyToManyField(blank=True, to='problems.language'),
        ),
    ]
