# Generated by Django 5.0.4 on 2026-03-13 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0011_problem_languages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='languages',
        ),
    ]
