# Generated by Django 5.0.4 on 2026-03-14 19:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0013_userproblemstatus'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProblemStatus',
            new_name='ProblemStatus',
        ),
    ]
